# Generated by Django 4.1.5 on 2023-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_major',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
