# Generated by Django 4.1.5 on 2023-02-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_major',
        ),
    ]
