# Generated by Django 4.1.5 on 2023-02-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_sudent_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sudent_major',
            new_name='studentmajor',
        ),
    ]
