# Generated by Django 4.1.5 on 2023-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_sudent_major_student_studentmajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
